# Generated by Django 3.2 on 2023-05-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comprobantes',
            new_name='Comprobante',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
